### PR TITLE
Hack to enable Cmd+X/C/V on macOS

### PR DESCRIPTION
**Pull request by nazar-pc**
Not yet sure if this will work, but it may fix https://github.com/subspace/space-acres/issues/145 (or rather hack around it)

### CODE REVIEW

**Comment by nazar-pc** [comment]
@abhi3700 or @DianaPertseva can you try https://github.com/subspace/space-acres/actions/runs/9886028404 (built from this PR) to see whether it helped or not

**Comment by abhi3700** [comment]
> @abhi3700 or @DianaPertseva can you try https://github.com/subspace/space-acres/actions/runs/9886028404 (built from this PR) to see whether it helped or not?

The issue is <kbd>cmd</kbd> key doesn't work, but <kbd>ctrl</kbd> does. Hence, <kbd>ctrl+c</kbd>/<kbd>ctrl+x</kbd>/<kbd>ctrl+v</kbd> works.
It seems the upstream lib has kept the same key shortcut for mac as that on Win laptops.

**Comment by nazar-pc** [comment]
> > @abhi3700 or @DianaPertseva can you try https://github.com/subspace/space-acres/actions/runs/9886028404 (built from this PR) to see whether it helped or not?
> 
> The issue is cmd key doesn't work, but ctrl does. Hence, ctrl+c/ctrl+x/ctrl+v works. Moreover, in the older macs, ctrl doesn't come. So, it's concerning there. But on the new ones, it's manageable.
> 
> It seems the upstream lib has kept the same key shortcut for mac as that on Win laptops.

I know that very well, but that is not what I'm asking here.
I'm asking you to check the liked test build that contains a potential workaround to see if it works with Cmd (see PR title).

**Comment by nazar-pc** [comment]
Doesn't work unfortunately

**Pull request closed without merging**
