### PR TITLE
feat: add feedback button

### PR DESCRIPTION
**Pull request by hunjixin**
Resolves https://github.com/subspace/space-acres/issues/154.  have tried linkbutton, but the style is not consistent with other button. so use button and uri launcer solution.

### CODE REVIEW

**Comment by hunjixin** [comment]
@nazar-pc please review

**Comment by EmilFattakhov** [comment]
@nazar-pc we can build a new custom Typeform with multiple options (leave feedback, report an issue, suggest a feature etc) as a start, and cc you on any replies to it. Would that be good enough, or you'd prefer something better from the start?

**Comment by nazar-pc** [comment]
We usually collect issues on the forum or Discord with verified stuff going to Discord. So it seems like not a great fit for the TypeForm. With features we also have a lot of ambiguity: forum, discord channel, GitHub. Basically a bunch of places where feature requests can arrive.

**Comment by EmilFattakhov** [comment]
I see, in this case something like LinkTree could be the landing page you referred to, with different options to open an issue on GitHub, create a forum post, or look for some support via Discord.

**Comment by EmilFattakhov** [comment]
@nazar-pc would [this](https://linktr.ee/subspace_network?utm_source=linktree_admin_share) be okay?

**Comment by nazar-pc** [comment]
Looks fine to me, will survey be another link in there?

**Comment by EmilFattakhov** [comment]
Yep, will add it.

**Pull request merged**
